### ISSUE TITLE
Sysdig generic (statically linked) binary for older kernel?

### ISSUE THREAD

**Issue by con-f-use** [draios/sysdig#1023]
This is not an issue rather than a (quiet specific) question. 

Is there a binary package of sysdig available that is statically linked and works on version 2.6.38 (64Bit) of the Linux kernel? If not how would I go about building it from source?

sysdig is pretty much the only tool available that solves a specific problem of mine. But I need to run it on fairly old appliances with said kernel, and I don't want to install alot of libraries on them by hand.

**Comment by ldegio** [comment]
the sysdig userland components are already statically linked, so there shouln't be problems running them anywhere.

The kernel module will have to be built for kernel 2.6.38. This is no problem (sysdig's module works seamlessly on kernels stating at 2.6.32, and on older kernels with some work), but by default the module is compiled from sources by DKMS when you install the sysdig package on your distro, which might be a problem for you because it requires some dependencies (e.g. gcc and kernel headers). The solution is compiling the module against the same kernel on another machine and then insmod-ing it manually. At that point you should be able to just run the standard sysdig binary. 

I'm closing the issue, feel free to hit the mailing list in case you need more info.

**Comment by con-f-use** [comment]
Thank you. And sorry for the non-issue spamming here. I didn't see another option. Will consult the mailing list for further inquires, but it seems promising.
