### ISSUE TITLE
Misleading error message when fd limit breached

### ISSUE THREAD

**Issue by ghost** [draios/sysdig#1230]
On systems where the number of active processes is greater than the file descriptor limit that `sysdig` executes under, execution fails at startup in [scap_open_live_int](https://github.com/draios/sysdig/blob/80f2142ac22110701e2f1e9b048b4eb79caf2639/userspace/libscap/scap.c#L408-L418) with the following output:

```
# sysdig
error creating the process list. Make sure you have root credentials
```

`strace` shows that this is preceded by an `EMFILE` return code from `open("/proc/1/status", O_RDONLY)` - could that be detected and a more useful error message returned to indicate that bumping the ulimit should help?

**Comment by kristopolous** [comment]
Would a more descriptive error message with some suggestions reach this goal or do you expect some logic underneath to better detect this class of failure?

**Comment by jayaddison** [comment]
@kristopolous If it's possible to detect this particular failure/error code (I *think* it is, but I don't know if it's guaranteed to fail at the same line of code in all cases) and tell the operator that it was due to a file descriptor limit that would seem 'optimal' but if it's significantly easier to add, simply an updated message/list of suggestions would be an improvement
