### ISSUE TITLE
Getting error: PERF_EVENT_IOC_SET_BPF: File exists, when trying to run BPF container based sysdig on COS with pre-emptible nodes.

### ISSUE THREAD

**Issue by xamox** [draios/sysdig#1241]
On a GKE node that is running COS.  Tried running docker based container using both methods (--net=host) listed here: https://github.com/draios/sysdig/wiki/eBPF#container-mode-recommended.

Both had the same issue.  This only appears to happen on pre-emptible nodes, if i use a standard node sysdig appears to work.  I may also file a ticket with google to see if they have some reasoning behind it.

```
sudo docker run -it --name sysdig --privileged --net=host -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro -v /etc:/host/etc:ro -e SYSDIG_BPF_PROBE="" sysdig/sysdig
* Setting up /usr/src links from host
ls: cannot access '/host/usr/src': No such file or directory
* Mounting debugfs
Found kernel config at /proc/config.gz
* COS detected (build 10895.23.0), downloading and setting up kernel headers
* Downloading https://storage.googleapis.com/cos-tools/10895.23.0/kernel-src.tar.gz
* Extracting kernel sources
* Configuring kernel
* Trying to compile BPF probe sysdig-probe-bpf (sysdig-probe-bpf-0.23.1-x86_64-4.14.56+-b254e92acc36dbf8d201e7d7d40738a9.o)
* BPF probe located, it's now possible to start sysdig
root@gke-dev-k8s-uw1-n1-highmem-16-prempti-23bcc4fa-0mp5:/# sysdig
* Mounting debugfs
Found kernel config at /proc/config.gz
* BPF probe located, it's now possible to start sysdig
PERF_EVENT_IOC_SET_BPF: File exists
root@gke-dev-k8s-uw1-n1-highmem-16-prempti-23bcc4fa-0mp5:/#
```

**Comment by gianlucaborello** [comment]
Thanks for reporting this.

Can you confirm again that the key difference is the preemptible in your use case? Because I can't replicate it on my side on a preemptible instance, but I know that for some reason on COS I can't seem to be able to run two instances of sysdig at the same time, or more generally two eBPF programs that might be attached to the same kernel events, but I haven't had time to look into that yet, since I considered it a relatively small priority and it works well anywhere else.

So, can you confirm that on this host you don't have any other eBPF program running, such as another sysdig instance, or perhaps the Sysdig Monitor/Secure agent? Because in that case, I'll definitely raise the priority for this.

Thanks

**Comment by xamox** [comment]
Okay, yep that is exactly the issue. So I was running falco with BPF as a daemonset on these nodes.  What I didn't realize is one of the nodes I tested on had taints so falco wasn't running on this node hence why I thought it wasn't working on preemptible nodes and working on standard, but it in fact doesn't appear to matter, the issue appears to be that falco is using BPF and when I try and run sysdig on the same node as a container where falco is already running then it throws the `PERF_EVENT_IOC_SET_BPF: File exists` error.  Let me know if you need anymore info.

I'm using GKE 1.10.7-gke.1 with COS.

```
root@gke-dev-k8s-uw1-n1-highmem-16-prempti-23bcc4fa-nwzd:/# uname -a
Linux gke-dev-k8s-uw1-n1-highmem-16-prempti-23bcc4fa-nwzd 4.14.56+ #1 SMP Sat Aug 11 23:13:59 PDT 2018 x86_64 GNU/Linux
```

**Comment by gianlucaborello** [comment]
I found the issue, the kernel didn't support attaching multiple eBPF programs to the same perf event up until 4.15 (https://github.com/torvalds/linux/commit/e87c6bc3852b981e71c757be20771546ce9f76f3), and since COS uses 4.14 that's what we get.

Now, fixing this doesn't really sound easy and on top of my head I can't imagine how I could do that (e.g. pinning the eBPF programs to the BPF FS to make them persistent and reuse them across invocations?), I promise I'll think about it but this is heavily mitigated by the fact that this issue is fixed in 4.15.

**Comment by gianlucaborello** [comment]
As promised, I thought a bit about it. The solutions I see are two, posting here so we don't forget in the future:

1) Create and persist a number of N BPF_MAP_TYPE_PERF_EVENT_ARRAY maps via the BPF fs (where N is the maximum number of consumers allowed): the first sysdig consumer that starts creates the BPF program and maps and attaches them to the tracepoint event. Each successive consumer will detect they're already there and will grab one of the free maps and will use those to open a brand new ring buffer via perf_event_open. The BPF programs need to be changed to do the fanout of the events across all these N maps.

2) Don't use tracepoints and instead offer the option to do system call instrumentation via kprobes, this way we effectively work around this 4.14 limit by paying a bit more in overhead. Essentially we create a brand new kprobe event for every instance, which should be possible I believe.

I'd be tempted to go with number 2, since I already have some code to deal with kprobes/uprobes in sysdig that will be published at some point.

**Comment by xamox** [comment]
@gianlucaborello Awesome, thanks for the follow up and digging into the issue.  I'm not sure I have enough insight into how sysdig works to weigh in on a solution, but it does appear that GKE is planning to stick with 4.14 as it's base for a while (https://cloud.google.com/container-optimized-os/docs/release-notes). At least december according to that link.  Not sure how much work it is for you, it would be nice to be able to run falco and sysdig in tandum as I'm assuming falco will proactively monitor and then I would use sysdig to do deep investigations when I have any issues, but I also understand this maybe lower on the priority map especially if it is fixed in 4.15 kernel.

**Comment by jaychan-q** [comment]
how can we have both sysdig and falco running in GKE COS. we have to lose one for another at this time as it gives the below error. i was already running sysdig and when trying to configure falco got this error

```* BPF probe located, it's now possible to start falco
Tue Apr 21 22:19:15 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Tue Apr 21 22:19:15 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Tue Apr 21 22:19:15 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue Apr 21 22:19:15 2020: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Tue Apr 21 22:19:16 2020: Unable to load the driver. Exiting.
Tue Apr 21 22:19:16 2020: Runtime error: PERF_EVENT_IOC_SET_BPF: Errno 17. Exiting.```

Thanks
Jay

**Comment by nathan-b** [comment]
@jaychan-q What version of GKE COS are you running?

**Comment by jaychan-q** [comment]
```$ uname -r
4.14.138+
```

**Comment by jaychan-q** [comment]
@nathan-b Tried running gke 1.15.9-gke.24 and that has kernel 4.19. Both sysdig and falco are operational. Thanks for your help

**Comment by nathan-b** [comment]
Glad this resolved your issue!

**Comment by DannyPat44** [comment]
Question on this! Would you expect to see a similar issue attempting to run Falco with the gRPC server enabled?

**Comment by nathan-b** [comment]
Hi @DannyPat44 . Do you mean attempting to run Falco on GKE? Both Falco and Sysdig will run into the same problem, and both have the same solution.
