### ISSUE TITLE
How to debug net.error.count? Where does this metric come from?

### ISSUE THREAD

**Issue by max-rocket-internet** [draios/sysdig#1291]
I have a process that creates a peak in the metric `net.error.count`. I would really like to debug this further but I not sure how. This metric doesn't come from interface statistics.

So where does it come from?
How I can see this metric without Sysdig when I'm logged into the host?
Where in this repo is the code that generates this metric?

Any help would be appreciated.

**Comment by ldegio** [comment]
I'm assuming by net.error.count you mean the Sysdig Monitor metric. If that's the case, that metric counts how many errors have been generated by operations on network socket file descriptors.

To understand what the cause is, I would generate a trace file from Sysdig Monitor and then do something like:

`> sysdig -r file.scap fd.type=ipv4 and evt.failed=true`

Which will show every single failed operation on IPv4 sockets. Make sure to use the latest version of sysdig which containes some fixes to properly recognize getsockopt errors.

**Comment by max-rocket-internet** [comment]
OK thank you @ldegio !

Did I miss documentation for this? Or is it non-existent?
