### ISSUE TITLE
sysdig does not register evt.type=open at all

### ISSUE THREAD

**Issue by slashbeast** [draios/sysdig#1309]
Hi,

I am running sysdig on two separated Gentoo systems with vanilla manually built kernel. I've noticed that sysdig is unable to pick any evt.type=open, but it does register openat calls. I tried the opensnoop from perf-tools too and it also does not register anything. I suspect that I must miss some kernel symbols that let sysdig and other similar tools trace open() calls but I am unable to find it, Do you have a list of kernel symbols that are required by SYSDIG to be operational?

    sysdig evt.type=open

does not see anything.

dev-util/sysdig-0.24.2
kernel 4.19.12

**Comment by sanmai-NL** [comment]
@slashbeast How did you manage to `emerge` Sysdig? An old, masked version of glibc turned out to be a dependency. I received a warning that installing it could cause userland instability. Not sure yet whether this old version would replace the system glibc. The Gentoo community content suggests so, in my eyes.

**Comment by fff7d1bc** [comment]
The sysdig does not depends on any particular version of glibc in it's ebuilds, and doing a downgrade of glibc is a sure way to brick your system unless you really know how to do it.

Just run `emerge sysdig` and that's all. I just installed `dev-util/sysdig-0.27.1-r100` , then `modprobe sysdig-probe` and it just works.
