### ISSUE TITLE
Secure Boot

### ISSUE THREAD

**Issue by phill0452** [draios/sysdig#1451]
Hi guys,

More of a question than an issue. We are using sysdig to gather account information associated with changes activity. We found on some Oracle 4.1.12-124.24.3.el6uek.x86_64 systems that sysdig would not load.

$ sudo sysdig | more
error opening device /dev/sysdig0. Make sure you have root credentials and that the sysdig-probe module is loaded.

Further review showed
$ sudo sysdig-probe-loader

/usr/bin/sysdig-probe-loader: line 333: [: -v: unary operator expected

Unloading sysdig-probe, if present
Skipping dkms install for UEK host
Trying to load a system sysdig-probe, if present
Trying to find precompiled sysdig-probe for 4.1.12-124.24.3.el6uek.x86_64
Found kernel config at /boot/config-4.1.12-124.24.3.el6uek.x86_64

Found precompiled module at ~/.sysdig/sysdig-probe-0.24.2-x86_64-4.1.12-124.24.3.el6uek.x86_64-57f7051a3912c4a3849daf981b71d1c6.ko, loading module

insmod: error inserting '/root/.sysdig/sysdig-probe-0.24.2-x86_64-4.1.12-124.24.3.el6uek.x86_64-57f7051a3912c4a3849daf981b71d1c6.ko': -1 Required key not available

We discovered that these systems are configured in secure boot mode. 

This page tells me that I should be able to add a key to the secure boot list
https://docs.oracle.com/en/engineered-systems/exadata-database-machine/dbmsq/exadata-security-features.html#GUID-8CE2452D-5C34-4A11-9C3F-38B0E648E701

And that is as far as I've got! Is there a key that I can use to import into secure boot?

**Comment by charles-dyfis-net** [comment]
Your problem has nothing to do with secure boot itself -- secure boot is used for the EFI bootloader to verify the kernel. `sysdig-probe-loader` happens long, long after the kernel is already loaded. 

Where it presumably ties into your problem, however, is that when built with `EFI_SECURE_BOOT_SIG_ENFORCE`, Linux only loads signed kernel modules if-and-only-if it was booted with Secure Boot. That's not the Secure Boot / UEFI infrastructure checking the signatures, though -- it's the Linux kernel itself, and you could very well turn on that signature checking even if you *weren't* using Secure Boot at all (`CONFIG_MODULE_SIG_FORCE=y` will do that, f/e).

Take a look at `/proc/keys` to see which public keys are trusted.

**Comment by stfast** [comment]
If you have Secure Boot enabled than you must sign compiled sysdig's scap kernel module.

Core of the solution is one line:

$ mokutil --import /var/lib/dkms/mok.pub

Here are the details.

When you install sysdig with:

curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | su curl -s https://s3.amazonaws.com/download.draios.com/stable/install-sysdig | sudo bash

You get:

$ sysdig
Unable to load the driver
error opening device /dev/scap0. Make sure you have root credentials and that the scap module is loaded: No such file or directory

$ modprobe scap
modprobe: ERROR: could not insert 'scap': Key was rejected by service

Than you have to sign scap module with DKMS public key:

$ mokutil --import /var/lib/dkms/mok.pub
input password: 
input password again:

You will have to enter this password in BIOS after reboot and MOK enrollment. 

After reboot with open VM console you get poped with MOK enrollment and don't miss key-press, because it asks you only once:

$ reboot

Now you enroll MOK in VM console:

![Screenshot 2024-10-24 at 13 44 09](https://github.com/user-attachments/assets/071fdbc6-051d-47f7-9b79-2493daf112ce)

![Screenshot 2024-10-24 at 13 44 17](https://github.com/user-attachments/assets/582f6c82-f074-427b-b20d-eaa055ca0764)

![Screenshot 2024-10-24 at 13 44 17](https://github.com/user-attachments/assets/dce94695-b267-4e57-9c6c-39a8621c00f2)

![Screenshot 2024-10-24 at 13 44 26](https://github.com/user-attachments/assets/eda108e2-68d0-4db3-ac06-226d304f58ce)

![Screenshot 2024-10-24 at 13 44 30](https://github.com/user-attachments/assets/f8ea5696-5598-4a8c-a5a1-067fedd2c135)

![Screenshot 2024-10-24 at 13 44 37](https://github.com/user-attachments/assets/93e30786-0b8b-421c-b2fe-d28df642aa70)

![Screenshot 2024-10-24 at 13 44 45](https://github.com/user-attachments/assets/cdddafda-4bf3-4845-bbbe-cdbf89d40680)

![Screenshot 2024-10-24 at 13 44 54](https://github.com/user-attachments/assets/e9df01e5-ec11-4f2a-b421-9ed0e029bba8)

![Screenshot 2024-10-24 at 13 45 09](https://github.com/user-attachments/assets/d2ca53ad-d1fa-44f9-8050-a85bb3ead1bb)

After MOK enrollment reboot, now check:

$ cat /var/log/messages |grep secure
Oct 24 12:52:01 moja-fedorca kernel: secureboot: Secure boot enabled
Oct 24 12:52:01 moja-fedorca kernel: secureboot: Secure boot enabled
Oct 24 13:06:52 moja-fedorca kernel: secureboot: Secure boot enabled
Oct 24 13:06:52 moja-fedorca kernel: secureboot: Secure boot enabled
Oct 24 13:26:49 moja-fedorca kernel: secureboot: Secure boot enabled
Oct 24 13:26:49 moja-fedorca kernel: secureboot: Secure boot enabled
Oct 24 13:45:25 moja-fedorca kernel: secureboot: Secure boot enabled
Oct 24 13:45:25 moja-fedorca kernel: secureboot: Secure boot enabled

$ cat /var/log/messages |grep integrity
..
Oct 24 13:45:25 moja-fedorca kernel: integrity: Platform Keyring initialized
Oct 24 13:45:25 moja-fedorca kernel: integrity: Machine keyring initialized
Oct 24 13:45:25 moja-fedorca kernel: integrity: Loading X.509 certificate: UEFI:db
Oct 24 13:45:25 moja-fedorca kernel: integrity: Loaded X.509 cert 'Microsoft Windows Production PCA 2011: a92902398e16c49778cd90f99e4f9ae17c55af53'
Oct 24 13:45:25 moja-fedorca kernel: integrity: Loading X.509 certificate: UEFI:db
Oct 24 13:45:25 moja-fedorca kernel: integrity: Loaded X.509 cert 'Microsoft Corporation: Windows UEFI CA 2023: aefc5fbbbe055d8f8daa585473499417ab5a5272'
Oct 24 13:45:25 moja-fedorca kernel: integrity: Loading X.509 certificate: UEFI:db
Oct 24 13:45:25 moja-fedorca kernel: integrity: Loaded X.509 cert 'Microsoft Corporation UEFI CA 2011: 13adbf4309bd82709c8cd54f316ed522988a1bd4'
Oct 24 13:45:25 moja-fedorca kernel: integrity: Loading X.509 certificate: UEFI:db
Oct 24 13:45:25 moja-fedorca kernel: integrity: Loaded X.509 cert 'Microsoft UEFI CA 2023: 81aa6b3244c935bce0d6628af39827421e32497d'
Oct 24 13:45:25 moja-fedorca kernel: integrity: Loading X.509 certificate: UEFI:MokListRT (MOKvar table)
Oct 24 13:45:25 moja-fedorca kernel: integrity: Loading X.509 certificate: UEFI:MokListRT (MOKvar table)
Oct 24 13:45:25 moja-fedorca kernel: integrity: Loaded X.509 cert 'Red Hat, Inc.: fedoraca: b280c7ae6b884e0f4d2a0d8724c25eaf6c65c326'
Oct 24 13:45:25 moja-fedorca kernel: integrity: Loading X.509 certificate: UEFI:MokListRT (MOKvar table)
Oct 24 13:45:25 moja-fedorca kernel: integrity: Loading X.509 certificate: UEFI:MokListRT (MOKvar table)
Oct 24 13:45:25 moja-fedorca kernel: integrity: Loaded X.509 cert 'DKMS module signing key: 605ddc47091299fc03fa7fad0c0b7a572f5901b6'
Oct 24 13:45:27 moja-fedorca systemd[1]: Reached target integritysetup.target - Local Integrity Protected Volumes.

$ modprobe scap

$ sysdig
18 13:52:19.476092630 1 sysdig (1086.1086) > switch next=0 pgft_maj=86 pgft_min=705 vm_size=65168 vm_rss=13856 vm_swap=0
19 13:52:19.476144934 1 <NA> (<NA>.0) > switch next=1086(sysdig) pgft_maj=0 pgft_min=0 vm_size=0 vm_rss=0 vm_swap=0
21 13:52:19.476277761 1 sysdig (1086.1086) > switch next=0 pgft_maj=86 pgft_min=705 vm_size=65168 vm_rss=13856 vm_swap=0
22 13:52:19.476652607 1 <NA> (<NA>.0) > switch next=1086(sysdig) pgft_maj=0 pgft_min=0 vm_size=0 vm_rss=0 vm_swap=0
33 13:52:19.476948588 1 sysdig (1086.1086) > switch next=0 pgft_maj=87 pgft_min=707 vm_size=65168 vm_rss=14040 vm_swap=0
34 13:52:19.477188463 1 <NA> (<NA>.0) > switch next=1086(sysdig) pgft_maj=0 pgft_min=0 vm_size=0 vm_rss=0 vm_swap=0

$ csysdig

![Screenshot 2024-10-24 at 17 29 04](https://github.com/user-attachments/assets/0f775d5d-7531-4053-a9d1-c316483cd87d)

All done!

You are also safe on kernel update or system upgrade, since scap kernel module is recompiled and signed implicitly during update/upgrade process.

![Screenshot 2024-10-24 at 17 30 10](https://github.com/user-attachments/assets/ab7b0199-d609-408f-ac5f-1460b29e43b5)
