### ISSUE TITLE
Consider moving `libscap` and `libsinsp` out of sysdig

### ISSUE THREAD

**Issue by krisnova** [draios/sysdig#1499]
Right now these libraries are very powerful but are hard to vendor and propose changes to without getting the `sysdig` CLI tool involved. By having independent versions of the libraries in independent libraries we could easily vendor them to our liking independently.

Just a thought, as we look at how we vendor them in Falco, we are subject to having to define the `sysdig` directory instead of vendoring the libraries like the other libraries (jq, grpc, etc) we vendor.

**Comment by mstemm** [comment]
I'm not sure I understand the goal of separating the sysdig libraries and programs. These two libraries are the bulk of the code in sysdig, and there would still be a very tight dependency between the sysdig programs and the libraries they utilize.

If you're trying to change the falco build process so sysdig can be downloaded and compiled like any other third-party package, that would be really easy. The sysdig build process already builds static libraries for libsinsp/libscap, and falco could link against them like any other third-party package. The driver would also be easy to build, you'd just have to make the probe name configurable when building the driver.

**Comment by bryanseay** [comment]
@kris-nova Can you define `hard to vendor`? 

Interface segregation would go a long way.

**Comment by nathan-b** [comment]
I think @mstemm 's suggestion gets us like 90% of the way there. We would love to define a cleaner api for `libscap` and `libsinsp`. It's great to have Falco as a consumer of these libraries because it prevents the heavy coupling between the library code and the sysdig command line tool that uses the libraries.

**Comment by speedyguy17** [comment]
I'm on board with mark, that seems reasonable, as I have concerns about splitting the repos as is:

1) splitting repos incurs a very real cost. This cost would be most apparent to oss-sysdig developers, who now have to edit the library, and then go to the "sysdig" repo which effectively just holds a CLI tool. this change does nothing for them other than make their lives more difficult. Their question would be, why can't the thin cli tool exist in the same repo? That's silly. Consider something like llvm. You clone llvm, and you get the library, but you also get a ton of user space utilities that are reference users of the library....clang, clang-format, etc.

2) the libraries are littered with explicit dependencies to proprietary code, which are then compiled out in OSS releases. It seems wrong to create a repo which we want to be a high-quality open source library without attacking the problems that hamper the one we currently have. This would segregate the "ugly" parts of the codebase in exactly the way we don't want to....in the new repo instead of the existing one. The best value for the community would be fixing what we already have, I think.

3) I think this is (in my opinion) a poor technical decision. If we are to explore such an option, I want to make sure we've exhausted every other possibilities....like can we just rename that repo to what it more actually is, like "libsinsp" or "oss-sysdig" or something?

**Comment by adalton** [comment]
I also agree with @mstemm.  The `sysdig` tool is, in some ways, the reference implementation of a client of `libsinsp`.  I don't see a lot of value is separating that reference implementation from the library.

**Comment by adalton** [comment]
One question that might help us decide is "How often do we modify `libsinsp` in a way that changes the API boundary between `sysdig` and the library?"  If the answer to that is "not often", then separating them might not be so bad.

**Comment by nathan-b** [comment]
Technically we did solve this one :)
