### ISSUE TITLE
Falco failed to start

### ISSUE THREAD

**Issue by zduymz** [draios/sysdig#1634]
I found some closed issues #846 related to pre-compile not found. But there is no a real solution.
How do i know what falco version support what kernel.
I'm using version `0.22.1` on EKS
```
Found kernel config at /host/boot/config-4.14.177-139.253.amzn2.x86_64
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-a259b4bf49c3330d9ad6c3eed9eb1a31954259a6-x86_64-4.14.177-139.253.amzn2.x86_64-59b34a961243b89a546a1522ae9e1b40.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the Falco community
Sat May 16 00:49:43 2020: Unable to load the driver. Exiting.
Sat May 16 00:49:43 2020: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.
```

**Comment by leodido** [comment]
This issue belongs to httsp://github.com/falcosecurity/falco

Anyway, the log says it all: there is no prebuild kernel module for Amazon Linux 2 kernel 4.14.177-139.253.

This because that version is trying to download it from the old prebuild drivers repo (https://s3.amazonaws.com/download.draios.com). The new script (you can try it using the code on Falco master or waiting for 0.23.0 to be released next week) downloads the drivers from the new repository: https://dl.bintray.com/falcosecurity/driver

**Comment by zduymz** [comment]
ok. sound good. thanks for your answer.
