### ISSUE TITLE
Can't find the module to be download

### ISSUE THREAD

**Issue by narezzi** [draios/sysdig#1713]
Found kernel config at /boot/config-5.7.0-kali1-amd64
* Trying to download precompiled module from https://download.sysdig.com/stable/sysdig-probe-binaries/sysdig-probe-0.27.1-x86_64-5.7.0-kali1-amd64-2a10ac4abd8623fc1716e7e871ee0ce4.ko
curl: (22) The requested URL returned error: 404

**Comment by nathan-b** [comment]
Normally, you are expected to build your own kernel module. There are some systems for which it is difficult or impossible to build a third-party kernel module, and for these, Sysdig (the company) hosts pre-built modules. Kali Linux is not a system that Sysdig prebuilds for.

If you post the entire log, we may be able to help you understand why your kernel module could not be built. 95% of the time it's because you don't have kernel headers installed.
