### ISSUE TITLE
Bash Command cannot be captured

### ISSUE THREAD

**Issue by irobert-rh** [draios/sysdig#1761]
We are not able to capture the bash command executed in the shell. 

I ssh to a machine with sysdig daemon running on it, and run a shell command like **whoami**.
```
proc.exe: -bash
proc.exeline: -bash
proc.exepath: bash
```
However, if I run the shell command with **-c**. I can get the actual command
```
proc.exe: bash
proc.exeline: bash -c whoami
proc.exepath: bash
```

**Comment by ldegio** [comment]
whoami might be a bash builtin in your system.

Bash builtins are commands that bash implements internally and therefore runs without calling any executable. For example, on my system `cd` and `which` are builtins and exhibit the behavior you are describing. When you use `bash - c` you are forcing bash to use the executable installed on the system instead of the builtin, and at that point sysdig can see it.

Do you see any event at all if you do a `proc.name=whoami` in the first scenario?
