### ISSUE TITLE
Options required argument missing, prints error, but still prints standard output

### ISSUE THREAD

**Issue by rmack** [draios/sysdig#322]
Issue: Normal sysdig output is printed even when missing required arguments after selected options. Proposed Fix: sysdig should exit gracefully.

For example when using a sysdig option such as  -i <chiselname>, --chisel-info <chiselname> and forgetting the required argument.

E.g.
sudo sysdig -i
sysdig: option requires an argument -- 'i'
7 11:38:36.336754302 1 sysdig (644) > switch next=0 pgft_maj=0 pgft_min=3562 vm_size=62728 vm_rss=6600 vm_swap=0 
8 11:38:36.336779571 0 <NA> (0) > switch next=31256(plugin-containe) pgft_maj=0 pgft_min=0 vm_size=0 vm_rss=0 vm_swap=0 
9 11:38:36.336787325 0 plugin-containe (31256) < poll res=0 fds= 
...

**Comment by Hefeweizen** [comment]
win32/getopt performs option parsing for us.  It seems to drop invalid options.

Because of this behaviour, I couldn't figure out a way to handle the error in sysdig.cpp; instead, I delved into getopt.  I consider this non-ideal because it breaks the modularity of the code.  To maintain the modularity, a better solution would be to extend getopt with a flag on each option for behaviour (quit or ignore).  But, I didn't want to immediately jump that far down.

So, I tried modifiying getopt directly, exit()ing on the known chisel names.  I can't get this to work.
https://github.com/Hefeweizen/sysdig/tree/bug322

My time is short now; I'll take a look at an alternate approach later.

**Comment by rmack** [comment]
On Linux this is required to fix the problem.
sysdig/userspace/sysdig/sysdig.cpp

            // getopt_long : '?' for an ambiguous match or an extraneous parameter 
            case '?' : 
                delete inspector;
                return sysdig_init_res(EXIT_FAILURE);

I haven't yet checked if the win32/getopt does the same thing yet.

**Comment by rmack** [comment]
I have pushed the Linux fix to the dev branch and I am now looking into the Windows getopt side.
