### ISSUE TITLE
Add IN operator

### ISSUE THREAD

**Issue by frioux** [draios/sysdig#327]
Sometimes you want to filter on a set of things and it's a big hassle.  I propose an IN operator, like in SQL.  This:

    sysdig evt.type = open or evt.type = close or evt.type = read or evt.type = write

Could be

    sysdig evt.type IN '(' open close read write ')'

**Comment by Hefeweizen** [comment]
I like the idea.  Nitpicking on syntax, I dislike the () enclosed list.  Just having a '' enclosed list should work, it already does a good job of parsing quotes.

I don't think implementation is too bad because it could internally expand the "evt.type in 'val1 val2 val3'" to (evt.type=val1 or evt.type=val2 or evt.type=val3).  What about the syntax "event operator in 'val1 val2'"?  This would allow "proc.name contains in 'word1 word2 word3'"?

**Comment by frioux** [comment]
I don't really care about syntax either way.  I like your generalization; neat idea.  As long as NOT IN will work too of course.

**Comment by davideschiera** [comment]
@Hefeweizen How would that work with strings that contain a space (e.g. to translate a filter like `proc.args='a b' or proc.args='c d'`)?

**Comment by rmack** [comment]
Is SQL IN normally follows this paradigm to catch the issue @davideschiera mentions.

IN ('Paris','London'), so in his example it would look like this: proc.args IN ('a b','c d')

I will need to see if this syntax is doable.

**Comment by rmack** [comment]
Please see merge #330 for any information about how the new IN Clause works, thank you.
