### ISSUE TITLE
Some events are recognized by sysdig, but can't be filtered

### ISSUE THREAD

**Issue by dkogan** [draios/sysdig#329]
I haven't looked to see how common this is, but one such even is inotify_add_watch. Sysdig happily captures and reports this event, but a filter such as 'evt.type = inotify_add_watch' fails.

**Comment by rmack** [comment]
@dkogan 

Could you please be more specific about what you mean by failing, thank you.  I only ask because I ran this against the dev branch and it appears the filter is working well.

susdo sysdig evt.type = inotify_add_watch
44661 12:25:13.121905245 0 gmain (2571) > inotify_add_watch 
44663 12:25:13.121913735 0 gmain (2571) < inotify_add_watch 
44665 12:25:13.121917457 0 gmain (2571) > inotify_add_watch 
44666 12:25:13.121920688 0 gmain (2571) < inotify_add_watch 
44667 12:25:13.121922915 0 gmain (2571) > inotify_add_watch 
44668 12:25:13.121925249 0 gmain (2571) < inotify_add_watch 
44669 12:25:13.121927450 0 gmain (2571) > inotify_add_watch 
44670 12:25:13.121929703 0 gmain (2571) < inotify_add_watch 
44671 12:25:13.121931790 0 gmain (2571) > inotify_add_watch 
44672 12:25:13.121933639 0 gmain (2571) < inotify_add_watch 
44673 12:25:13.121935676 0 gmain (2571) > inotify_add_watch 
44674 12:25:13.121937505 0 gmain (2571) < inotify_add_watch 
44675 12:25:13.121939504 0 gmain (2571) > inotify_add_watch 
44676 12:25:13.121941563 0 gmain (2571) < inotify_add_watch

**Comment by dkogan** [comment]
Oh, I see. I was looking at the wrong branch, where your above invocation did not work. The current 'dev' branch DOES work, as you have seen. My mistake; sorry. Before filing I did double-check the validity of the bug report by doing

    $ ./sysdig -L | grep inotify
    > inotify_init(FLAGS8 flags)
    < inotify_init(FD res)

This happens even in the dev branch, which probably isn't right, since it says that inotify_add_watch isn't supported even though it actually is (albeit with no parsed args). Is this lack of parsed args what makes sysdig -L NOT report this?

**Comment by rmack** [comment]
@dkogan Let me look into tomorrow, thank you.

**Comment by rmack** [comment]
@dkogan What do you mean by "it says that inotify_add_watch isn't supported even though it actually is"? Providing the "**-L**, --list-events  **List the events that the engine supports**" and this shows it is supported under the **dev** branch?  Maybe I am not understanding your wording with your concern?

**Comment by dkogan** [comment]
As I understood it, events that sysdig knows about (i.e. it records them and can filter them) are all reported by "sysdig -L". Currently with the dev branch sysdig -L does NOT report inotify_add_watch. Is this correct?

**Comment by rmack** [comment]
@dkogan, It appears this is correct.  I am investigating a solution, thank you.

**Comment by Hefeweizen** [comment]
What's the threshold for listing events for -L?  What extra information should be available for this event that's not?
