### ISSUE TITLE
Failure to capture with more parameters

### ISSUE THREAD

**Issue by ronin13** [draios/sysdig#345]
```
 sysdig -p "%proc.pid %proc.name %evt.args %evt.dir" evt.type=kill and evt.arg.pid contains xmobar 
```

with 

kill -0 $(pidof xmobar)

prints

```
57864 zsh pid=53601(xmobar) sig=0  >
57864 zsh pid=53601(xmobar) sig=0  >
57864 zsh pid=53601(xmobar) sig=0  >
57864 zsh pid=53601(xmobar) sig=0  >
``` 
============

However, 

```
sudo sysdig -p "%proc.pid %proc.name %evt.args %evt.dir %evt.buffer" evt.type=kill and evt.arg.pid contains xmobar
```

prints nothing even when signals are sent.

Full log with dmesg and verbose=1 for the module: http://paste.wnohang.net/4f6b09
 

```
sysdig --version
sysdig version 0.1.72.r1335.gd7f05fc
   
```

**Comment by gianlucaborello** [comment]
I don't think this is documented anywhere, but by default all the fields listed in the output format must exist for the event in order to be printed, otherwise the event will be skipped. In this case, evt.buffer doesn't exist for the signal event, so that explains the behavior.

This behavior can be reverted by adding "*" as the first character of the output_format, so in your case it will become:
```
sudo sysdig -p "*%proc.pid %proc.name %evt.args %evt.dir %evt.buffer" evt.type=kill
```

And you should correctly see "NA" for the evt.buffer.

I'm leaving this open until we document this thing properly.

Also, where did you get this version? 0.1.72 is extremely old and certainly doesn't match the upstream version that you're using, since the signal event hasn't even been released yet and it's still in the dev branch.

**Comment by ronin13** [comment]
Yes, it is better to log when something is skipped, (even if documented) to avoid false negatives.

**Comment by ronin13** [comment]
Also, d7f05fc973080f5471af596cbcc8e2b2efc9e934 is the HEAD of the master  I built from.

**Comment by ronin13** [comment]
Works fine with asterisk in the output_format.

**Comment by gianlucaborello** [comment]
Thanks for confirming. So if you built from that commit where does the 0.1.72 come from?

**Comment by ronin13** [comment]
The PKGBUILD (from https://aur.archlinux.org/packages/sysdig-git/)  uses  git describe --long in the repo.

**Comment by gianlucaborello** [comment]
Interesting. At the moment we're using github releases which always create a lightweight tag, so git describe won't work by default. I guess we could tweak the build to replace the github's tag with an annotated one, but I don't know if it's really worth it. Also, it's important noticing that we're using tags for other purposes, so, even if we fix that, there's still a risk of picking the wrong tag. The right command line is more something like:

```
$ git describe --long --tags --match [0-9]*
0.1.99-38-gd7f05fc
```

Are you anyhow involved with the arch linux team to raise the concern? Otherwise I'll have to go bug them, shipping sysdig as version 0.1.72 is simply wrong.

Also, I know the Debian maintainer does some automatic tag parsing and it has always worked for Ubuntu and Debian.
