### ISSUE TITLE
Issue with process names over 15 characters

### ISSUE THREAD

**Issue by thetwinpeaks** [draios/sysdig#354]
Hello,
If the process with length 16 or more characters is running, Sysdig prints to it's repport only 15 first characters of it's name. 
For example: if the process name is 123456789012345678901234567 then Sysdig will record to it's report only 123456789012345 (i.e. without 678901234567 in the end).
How can this issue be solved ?

**Comment by frioux** [comment]
I'm running into this too, for what it's worth.

**Comment by ldegio** [comment]
This seems to be a limitation in the Linux Kernel. I tried to do a:

cat /proc/<pid>/comm

and I got 

123456789012345

Which is the same truncated value. There are a couple of ways to overcome this limitation:
1. launch sysdig with a custom printer that uses the executable line instead of the comm name. For example:
  sysdig -p"*%evt.num %evt.time %evt.cpu %proc.exeline (%thread.tid) %evt.dir %evt.type %evt.info" oc.name contains 12345
2. use csysdig, which uses exeline by default
