### ISSUE TITLE
install via docker fails (because dkms is looking for gcc-4.8, but container has 4.9)

### ISSUE THREAD

**Issue by PAStheLoD** [draios/sysdig#356]
image id: ca285327a39d

```
root@78249ebccf8d:/var/lib/dkms/sysdig/0.1.99/build# cat make.log 
DKMS make.log for sysdig-0.1.99 for kernel 3.16.0-4-amd64 (x86_64)
Fri May  8 04:16:19 UTC 2015
make: Entering directory '/host/usr/src/linux-headers-3.16.0-4-amd64'
make[1]: Entering directory `/host/usr/src/linux-headers-3.16.0-4-amd64'
/host/usr/src/linux-headers-3.16.0-4-common/arch/x86/Makefile:121: stack-protector enabled but compiler support broken
/host/usr/src/linux-headers-3.16.0-4-common/arch/x86/Makefile:136: CONFIG_X86_X32 enabled but no binutils support
/host/usr/src/linux-headers-3.16.0-4-common/Makefile:646: Cannot use CONFIG_CC_STACKPROTECTOR_REGULAR: -fstack-protector not supported by compiler
make[2]: gcc-4.8: Command not found
  LD      /var/lib/dkms/sysdig/0.1.99/build/built-in.o
  CC [M]  /var/lib/dkms/sysdig/0.1.99/build/main.o
/bin/sh: 1: gcc-4.8: not found

```

**Comment by gianlucaborello** [comment]
As a workaround, you can install gcc-4.8 inside the container with apt and run sysdig-probe-loader again.

As a long-term solution, I am willing to include both gcc 4.9 (default from Debian) and gcc 4.8, but that would make the Docker image size increase from 220MB to 300MB, so I was wondering if you are using a widestream distribution or not. If you are, it might be worth doing it, otherwise probably not.

From the kernel version you're running, I'm guessing it might be Debian 8 but I want to double check before taking further actions.

**Comment by PAStheLoD** [comment]
The host is a simple Debian Jessie machine, both 4.8 and 4.9 are installed. (Maybe because it started out as a Wheezy one.)

I would just detect the necessary one and execute apt-get update && apt-get install gcc-<req version>, but I'm not really familiar with the install proceess :)

**Comment by gianlucaborello** [comment]
The issue should be fixed now, I include both compilers in the docker image, discovering gcc version at runtime is not trivial because that same docker container must also run on a variety of RHEL distributions and there things are a bit different than in Debian.
