### ISSUE TITLE
sysdig build system conflates operating system paths with compiler flags

### ISSUE THREAD

**Issue by Pw7LK4HK4AfqN1RgiOaTdwxmNbOuGrpV** [draios/sysdig#367]
The sysdig build system uses "cmake", which conflates the concepts of "path on the OS filesystem" and the concept of "paths the compiler will accept to refer to things".

These two concepts are unrelated -- the compiler produces output that has no need to be related to the system it is running on.  During cross-compilation or using a compiler that supports "sysroot" these assumptions are violated and "sysdig" cannot be compiled.

Part of the problem is in functions inside CMake and part of the problem is in code in Sysdig's CMake build scripts.

In order to overcome these issues I had to patch the CMakeLists.txt file to hard-code the correct values in for paths to ncurses and zlib (patch: https://gist.github.com/Pw7LK4HK4AfqN1RgiOaTdwxmNbOuGrpV/db31bd6e8eb5292ecd88).

```
mkdir build
cd build
cmake \
    -DCMAKE_INSTALL_PREFIX= -DCMAKE_SYSTEM_NAME='Linux' \
    -DUSE_BUNDLED_ZLIB=OFF \
    -DUSE_BUNDLED_NCURSES=OFF \
    -Wno-dev \
    ..

KERNELDIR=/home/user/projectX/node/kernel/kernel-dir
export KERNELDIR

make HOST_CC=/usr/bin/cc
```

**Comment by gianlucaborello** [comment]
Hi,

A few random notes on this issue:

- You are right, cmake is not ideal for doing cross-compiling-like stuff. Have you by any chance checked http://www.vtk.org/Wiki/CMake_Cross_Compiling if there's some nice way through which you can give cmake some hints on where the build environment is located?

- I assume it doesn't apply to your case, but the simplest way would be to go with the static libraries we embed by default :) Again, I understand mine is just a provocative comment since if you took the time to discover the various USE_BUNDLED_*=OFF it means that you need them

- For zlib, have you tried passing the ZLIB_PREFIX to cmake before writing your patch? In theory it should be supported and documented here https://github.com/draios/sysdig/wiki/How-to-Install-Sysdig-from-the-Source-Code:

```
cmake -DUSE_BUNDLED_ZLIB=OFF -DZLIB_PREFIX=/opt/superzlib ..
```

- For ncurses, yes, for lack of time at the moment we just relied on the standard find_package provided by cmake. If you confirm the previous point about zlib works, we can easily add a NCURSES_PREFIX that you can pass to cmake to set compiler paths, like we do for zlib.

- I understand cmake is not as advanced as you'd like, but to its credit it works very well for our use cases and allowed us to save tons of time that we have focused on sysdig features. If you have a more elegant idea on how to solve this problem, please work on it and contribute to the project and we'll make sure to merge it :)

**Comment by Pw7LK4HK4AfqN1RgiOaTdwxmNbOuGrpV** [comment]
I tried to use -DZLIB_PREFIX in many combinations and was not able to make it go.  It kept wanting to look for a file on the filesystem instead of passing options to the compiler (there is no file that cooresponds to -lz, atleast none that you will be able to find).

I initially left the USE_BUNDLED_*_OFF out and it failed to compile entirely because the ./configure scripts that were called for ncurses lacked the options telling it the proper --host to compile for.

As for CMake's use, I think the biggest issue is mainly that it fails to handle common non-default things that autoconf has handled well for years and makes false base assumptions (like that the filesystem has answers about the compiler -- it does not -- you have to ask the compiler).  It's significantly more primitive than GNU autoconf (though I would avoid automake).

Data point: For the Linux distribution I maintain, I have 210 packages, the majority of them using GNU autoconf (or similar) and 3 (including Sysdig) using CMake.  Of the ones that use GNU autoconf (or similar), 10 need special ways to talk to the "configure" (mostly setting an environment variable telling it where a ncurses is -- CFLAGS='-I/include/ncurses' or similar).  All 3 instances of CMake require something different to make the project compile correctly.

**Comment by gianlucaborello** [comment]
I understand. Yes, cmake will definitely not help you if zlib is not available anywhere in the file system at the time you're running cmake. At the beginning I thought you were mentioning a "typical" cross-compile where you just point to a different root file system, but that doesn't seem to be the case.

At this point, I think the quickest way to solve this would be to add the option to explicitly set ZLIB_INCLUDE/NCURSES_INCLUDE/... when invoking cmake, and disabling the embedded and the find_package stuff when those options are set. Essentially, doing exactly what you did with your patch. If you care to clean it and make it work via cmake options, we can definitely merge it.
