### ISSUE TITLE
Add flag to sysdig/csysdig to allow passing K8S CA certificate

### ISSUE THREAD

**Issue by tobad357** [draios/sysdig#488]
Currently there doesn't seem to be a way to pass a K8S CA cert to the csysdig -k flag.
It is needed if using https to access the K8S API Server

**Comment by gianlucaborello** [comment]
Just to confirm, your API server is configured to kick you out if you don't have a valid certificate, right? Because at the moment we do support HTTPS, but not HTTPS certificate-based authentication, so if you're able to do "curl -k https://[user:password@]api_server", it should already work with sysdig.

**Comment by tobad357** [comment]
Very sorry.. It was late and I assumed it worked the same as dragent where you have to pass in your private ca cert.. It works fine now

The only thing missing (which is much lower priority) is to verify the private cert comin from the API server.
