### ISSUE TITLE
How can I run sysdig without dropping events?

### ISSUE THREAD

**Issue by mindscratch** [draios/sysdig#519]
I read the following on the [blog](https://sysdig.com/sysdig-vs-dtrace-vs-strace-a-technical-discussion/)

> Will sysdig slow down my system just like strace (the wise reader asks)? Well of course not. In this scenario, the event buffer fills up, and sysdig-probe starts dropping the incoming events. So you will lose a bit of trace information, but the machine, and the other processes running on it, will not be slowed down.

Are there settings I can use to perform a trace without having events dropped? For example, give sysdig more cpu, memory or let it write to disk vs. dumping to stdout.

**Comment by luca3m** [comment]
The sysdig kernel module will start dropping events when the sysdig userspace utility is not able to keep up processing them and so the buffer grows until it's full. The latter should be a rare case. To avoid it you can use tracefiles so sysdig has less work to do:

```
sysdig -w /trace.scap
```

and then to read the events:

```
sysdig -r /trace.scap
```

**Comment by mindscratch** [comment]
Thanks

**Comment by mikeguidry** [comment]
Any suggestions for my situation?

I have a lua script which is performing some filtering.  I thought it could happen in userland beforehand, but now I realize that the userland must read the kernel sceario before.  Sending tcp/ip to logstash via LUA script seems to be too slow sometimes with high usage processes taking place.

I just tried to:
mkfifo test
<term 1> sysdig -w test
<term 2> sysdig -r test -c lua_distro

and it fails...  if I perform sysdig write to a file, and then read it.. it may not be fast enough to analyze in the ways that I need it..

thanks ahead.

**Comment by ldegio** [comment]
@mikeguidry, if I correctly understand your scenario, you are trying to send TCP data from a chisel. 

This can definitely be an issue if you send the data from on_event(), because the sysdig capture pipeline is blocked until on_event() returns. If the network becomes slow, on_event() could block for long periods of time and cause event drops. 

I recommend that you decouple your approach and send the data to logstash from a separate process, using a pipe or a shared file to pass the data to this process
