### ISSUE TITLE
Segmentation Fault while tracing on CentOS 7

### ISSUE THREAD

**Issue by mindscratch** [draios/sysdig#520]
Info about the system:

* CentOS 7
* kernel 3.10.0-123
* sysdig 0.5

Command: sysdig -z -W 10 -C 1024 -w /var/foo.scap.gz -c echo_fds fd.port=80 and evt.buffer contains GeT > /dev/null

After some time (usually less than 10min), sysdig exits and prints "Segmentation fault".

Any tips on how to figure out what's going on?

**Comment by gianlucaborello** [comment]
Could you please

1) Make sure you're still reproducing it using the latest stable release, 0.6.0

2) If so, make sysdig crash again with gdb and get a stack trace. You can do something like:

```
# gdb --args sysdig -z -W 10 -C 1024 -w /var/foo.scap.gz -c echo_fds fd.port=80 and evt.buffer contains GeT
$ run
... wait until crash occurs ...
$ bt
```

If the resulting stack trace will be full of `?????` and unknown symbols, please use the sysdig binary you can find at https://s3.amazonaws.com/download.draios.com/stable/tgz/x86_64/sysdig-0.6.0-x86_64.tar.gz since it is not stripped of debugging symbols.

**Comment by mindscratch** [comment]
I'll give it a shot and report back.

**Comment by mindscratch** [comment]
I haven't tried the latest version yet, but I reran the command and after a few minutes got:

`Error in `sysdig': malloc(): smallbin double linked list corrupted: ...`

I can't simply copy/paste the stack trace, but the first line in the trace that references sysdig is this:

`sysdig(_ZNSs12_S_constructIPKcEEPcT_S3_RKSaIcESt20forward_iterator_tag+0x21)[0x4b5c31]`

**Comment by gianlucaborello** [comment]
Is there something else you could share? Any reason why the full stack trace can't be disclosed?

**Comment by mindscratch** [comment]
I'll try with the latest version this week. I can't disclose the full stack
trace because of business rules.

**Comment by mindscratch** [comment]
Running the latest version of sysdig (0.7.1) the original command I ran hasn't failed. Closing this issue.
