### ISSUE TITLE
sysdig 0.7.0 spectrogram mouse reporting doesn't work on OSX (iTerm/Terminal)

### ISSUE THREAD

**Issue by jfchevrette** [draios/sysdig#526]
It seems like even though mouse reporting is enabled in OSX's Terminal / iTerm, csysdig doesn't recognize the mouse events. Because of that, it is not possible to use the spectrogram drilldown feature on OSX when using iTerm or Terminal.

Normal clicking throughout the UI works fine. It looks like the problem is only with the drag operations.

This should be fairly easy to reproduce on an OSX machine. Just start iTerm or Terminal, connect to a server and run csysdig, then open the spectrogram and try to draw a selection box.

**Comment by jkottler** [comment]
Similar problem on Linux Mint 17.3 or Crunchbang++ in VMs on Windows either. On Mint, the message "Mouse input not supported in this terminal" is displayed. In CB++, nothing.

**Comment by ckmt** [comment]
I see the same behavior (clicking rows, etc. works, but clicks in the spectrogram have no discernible effect) with sysdig 0.8.8 on Arch Linux, under xterm, rxvt-unicode, and lilyterm (VTE-based).

**Comment by pmorch** [comment]
I've tried on an updated debian jesse with both gnome terminal logged in remotely over ssh, and a locally run xterm.

**Comment by richardrasu** [comment]
Same issues as everyone else here with sysdig 0.8.0 on ubuntu 15.10 (server) via iTerm2 v2.1.4 on OS X 10.11.3

**Comment by ldegio** [comment]
So the problem here is that many terminals, including iterm and the OS X terminal, have liberal/buggy implementations of xterm-1002, which prevents curses-based mouse drag detection from working.

These commits 
https://github.com/draios/sysdig/commit/5427245c4943f726baaf03838c8f5fde4e2b9cd7 
https://github.com/draios/sysdig/commit/e208dd2135525d7fdbe565d74cff5a2db2f974c2

change the spectrogram code to be based on two separate mouse clicks instead of having to drag the mouse. I tested the new behavior on terminal and iterm2 on OS X and on xterm and terminator on Ubuntu 14 and it seems to work as expected, but I would encourage everyone in this thread to give it a try and reopen if you still see issues.

**Comment by jkottler** [comment]
I noticed while working with a replay that the click-and-drag method worked *once the replay stopped*.

**Comment by ldegio** [comment]
@jkottler, by replay you mean when you read from a capture file? In that case yes, currently mouse selection starts working only when the whole file has been processes by the spectrogram.

**Comment by yujinqiu** [comment]
@ldegio   "  change the spectrogram code to be based on two separate mouse clicks instead of having to drag the mouse.  "  Do you mean click in two different point to select ?  I try many ways but all failed.   sysdig version 0.19.1  Iterm2 Build 3.1.5. 

```
. (click) 
        .(click) 
```

**Comment by axot** [comment]
I think separate mouse clicks not work in my OSX, I'm using 0.24.2. Any ideas?

**Comment by q2dg** [comment]
Please, reopen this issue. It's not solved.
I can't do anything with mouse in csysdig's spectogram shown in my Ubuntu's 20.04 gnome-terminal.
Thanks
