### ISSUE TITLE
Add sysdig-nodeps package

### ISSUE THREAD

**Issue by rrva** [draios/sysdig#530]
If you take care of building the kernel module outside of the normal packaging, the dependencies on gcc etc for sysdig are unnecessary.

I understand the standard sysdig package needs to depend on gcc for DKMS etc, but can we have a separate sysdig-nodeps package (debian/ubuntu) without any dependencies built in each release?

Any runtime dependencies should be referenced, but no compile-time deps for the driver.

**Comment by gianlucaborello** [comment]
That's definitely a good suggestion. Until this is implemented on our side, please notice that Debian/Ubuntu already repackage sysdig using the same convention (`sysdig`, with no dependencies, and `sysdig-dkms`): https://packages.debian.org/search?keywords=sysdig&searchon=names&suite=all&section=all

If you're fine with staying a couple versions behind the upstream, that will work for you.

**Comment by rrva** [comment]
I need this for debian jessie, and it seems awfully old what comes with the distro :(

**Comment by bcg62** [comment]
Looking for the same solution for centos, Really don't want to carry gcc around in production to keep sysdig.

**Comment by gianlucaborello** [comment]
Makes sense. Another very dirty possibility until this gets properly implemented is to just use the Docker container to run sysdig so the build toolchain is inside the container and won't mess with your system. And if that's still too much, you can also uninstall gcc/dkms inside the sysdig container (and break the dependency requirements using some combination of --force dpkg flags in an awful way, but who cares since it's an isolated container).

Of course, just temporary until someone can actually implement this.

**Comment by PaulCapestany** [comment]
Any timeframe for when/if this might get implemented? Requirement for `gcc` might make using sysdig in prod a non-starter for some...

**Comment by PaulCapestany** [comment]
Or, @rrva, is there much involved in building a kernel module yourself? (I'm generally totally fine building from source myself, not sure if there's more involved with kernel modules though, perhaps not?)
