### ISSUE TITLE
Overhead test report of sysdig

### ISSUE THREAD

**Issue by hzhaop** [draios/sysdig#536]
Hello,
I am trying to use sysdig to monitor process tcp connections on my production cluster.  The overhead of the agent is what I concerned most. 
As I know, the overhead of sysdig is related to the system load and the filter I use. Firstly, I test with no filter on my machine and the CPU usage is around 10%. Secondly, I run "dd if=/dev/zero of=/dev/null bs=1 count=50000k" command, the CPU usage is over 70%. 
My question is, is there a way to control CPU usage(less than 5%) no matter how heavy the system load, by sampling or just instrument some events(tcp connect) I am concerned? 
Further more, is there a overhead test report of sysdig so I can judge if it is suitable for my situation?

Thank you and sorry for my poor English.

**Comment by hzhaop** [comment]
Just inspired by cpulimit, can I send SIGSTOP and SIGCONT to control sysdig CPU usage? 
I tested just now, it works, but I am not quite familiar with the kernel space programming, I am wondering if there is some side-effect when I do so?

**Comment by ldegio** [comment]
Yes, the driver will capture even when you stop the user level application, because the collection is done in the context of the process producing the event.

Another couples of things you can try:
- using nice to set the priority of sysdig
- using sysdig cloud. This is a commercial product, so it might not be an option for you, but one of its basic features is the ability to cap CPU usage by using techniques like selective event dropping and subsampling.
