### ISSUE TITLE
Segmentation Fault csysdig on mac

### ISSUE THREAD

**Issue by KnoxAnderson** [draios/sysdig#606]
Segmentation faults happen two different ways during file processing of a sysdig capture
1. If any key is pressed during the time a file is being processed
2. If the terminal window is resized during the time a file is being processed

<img width="857" alt="screen shot 2016-06-07 at 12 48 30 pm" src="https://cloud.githubusercontent.com/assets/13387594/15872454/60f788fc-2cae-11e6-9fe3-7e386fdd1703.png">

**Comment by gianlucaborello** [comment]
@ldegio would you be able to look at these before the velocity conference? Since my talk is going to be a workshop and most people are going to use OSX, and these issues seem to just happen there, it would be good to see if they can get fixed.

I can also try to take a look if needed, but I'm not a csysdig expert.

**Comment by ldegio** [comment]
on it

**Comment by KnoxAnderson** [comment]
The version is 0.8.0

**Comment by ldegio** [comment]
spoken to @KnoxAnderson, looks like updating to the latest version fixes the issue. 
Closing.
