### ISSUE TITLE
Use sysdig to trace syscalls invoked by a docker container

### ISSUE THREAD

**Issue by shengying** [draios/sysdig#642]
Hi there,
I am now using sysdig to trace syscalls invoked by a docker container.
However, it seems that I cannot get the complete list of syscalls.
I wonder if sysdig ignores some frequent syscalls in the trace for performance consideration.
If so, how can I get a complete syscall list of a docker container?

Thanks,
Zhiyuan

**Comment by ldegio** [comment]
as far as I know you should see all of the system calls even if some of them are not fully decoded. What do you think you are missing?

**Comment by shengying** [comment]
Hi Idengio,
Thanks for you reply.
For nginx container (https://hub.docker.com/_/nginx/), I found "sendmsg" is missed by sysdig.

**Comment by ldegio** [comment]
is it completely missing or is it there but with no arguments decoded?

**Comment by shengying** [comment]
Hi Idengio,
It is completely missing. 
The output of sysdig version:
`sysdig version 0.11.0`
The environment details:
`VirtualBox 5.0.24, Ubuntu 16.04`

**Comment by ldegio** [comment]
sorry for the delay in answering this. I just run the nginx container you pointed to, and I don't see any usage of _sendmsg_ because nginx is using sendfile or writev to return the data. Here's a couple of relevant snippets: 

Static file:
`
1091 16:13:18.508115520 2 nginx (107355) > recvfrom fd=3(<4t>172.17.0.1:41582->172.17.0.2:http) size=1024 
1092 16:13:18.508117753 2 nginx (107355) < recvfrom res=78 data=GET / HTTP/1.1..User-Agent: curl/7.35.0..Host: 127.0.0.1:8090..Accept: */*.... tuple=NULL 
1093 16:13:18.508133176 2 nginx (107355) > stat 
1094 16:13:18.508161985 2 nginx (107355) < stat res=0 path=/usr/share/nginx/html/index.html 
1095 16:13:18.508166262 2 nginx (107355) > open 
1096 16:13:18.508180178 2 nginx (107355) < open fd=11(<f>/usr/share/nginx/html/index.html) name=/usr/share/nginx/html/index.html flags=65(O_NONBLOCK|O_RDONLY) mode=0 
1097 16:13:18.508181223 2 nginx (107355) > fstat fd=11(<f>/usr/share/nginx/html/index.html) 
1098 16:13:18.508183361 2 nginx (107355) < fstat res=0 
1099 16:13:18.508195539 2 nginx (107355) > writev fd=3(<4t>172.17.0.1:41582->172.17.0.2:http) size=238 
1100 16:13:18.508218345 2 nginx (107355) < writev res=238 data=HTTP/1.1 200 OK..Server: nginx/1.11.5..Date: Thu, 24 Nov 2016 00:13:18 GMT..Cont 
1101 16:13:18.508220274 2 nginx (107355) > sendfile out_fd=3(<4t>172.17.0.1:41582->172.17.0.2:http) in_fd=11(<f>/usr/share/nginx/html/index.html) offset=0 size=612 
1102 16:13:18.508237235 2 nginx (107355) < sendfile res=612 offset=612 
`

Dynamic content:
`
568 16:25:40.269482914 3 nginx (127413) > recvfrom fd=11(<4t>127.0.0.1:58146->127.0.0.1:tproxy) size=4096 
569 16:25:40.269486230 3 nginx (127413) < recvfrom res=151 data=HTTP/1.1 200 ..Content-Length: 58..Date: Thu, 24 Nov 2016 00:25:40 GMT..Connecti tuple=NULL 
570 16:25:40.269500254 3 nginx (127413) > readv fd=11(<4t>127.0.0.1:58146->127.0.0.1:tproxy) 
571 16:25:40.269502409 3 nginx (127413) < readv res=0 size=0 data= 
572 16:25:40.269508394 3 nginx (127413) > close fd=11(<4t>127.0.0.1:58146->127.0.0.1:tproxy) 
573 16:25:40.269509146 3 nginx (127413) < close res=0 
574 16:25:40.269538148 3 nginx (127413) > writev fd=3(<4t>172.17.0.9:45262->172.17.0.12:http-alt) size=178 
575 16:25:40.269604124 3 nginx (127413) < writev res=178 data=HTTP/1.1 200 ..Server: nginx/1.10.1..Date: Thu, 24 Nov 2016 00:25:40 GMT..Conten 
576 16:25:40.269613189 3 nginx (127413) > write fd=4(<f>/var/log/nginx/access.log) size=111 
577 16:25:40.269629657 3 nginx (127413) < write res=111 data=172.17.0.9 - - [24/Nov/2016:00:25:40 +0000] "GET /simpleWebJava/TestServlet HTTP 
`

I'm closing the issue, but feel free to reopen if you think I'm missing something.
