### ISSUE TITLE
Grouping by tracers tags not available in fdbytes_by chisel

### ISSUE THREAD

**Issue by bencer** [draios/sysdig#679]
I've been using Sysdig tracers to perform some measurements in my code. When trying to use span tags as the grouping filter in the fdbytes_by chisel I get no results.

When I use any other grouping filter it works:

```
$ sudo sysdig -r capture.scap -c fdbytes_by "thread.tid"
Bytes               thread.tid          
--------------------------------------------------------------------------------
2.47G               1937
1.00G               2260
[etc]
```

```
$ sudo sysdig -r capture.scap -c fdbytes_by fd.name "fd.type=file and evtin.span.tag[0] contains handler" 1 ↵
Bytes               fd.name             
--------------------------------------------------------------------------------
2.50G               /tmp/blob.bin.4
12.00M              /tmp/blob.bin.2
11.25M              /tmp/blob.bin.3
9.00M               /tmp/blob.bin.1
```

but when using span tracers I get no result:

```
$ sudo sysdig -r capture.scap -c fdbytes_by "span.tags"                                                  
Bytes               span.tags           
--------------------------------------------------------------------------------

```
I can confirm the span.tags actually do exist in my capture:
```
$ sudo sysdig -r capture.scap "span.ntags >= 1" | head -n 5
768942 07:32:11.602785193 0 python (2185) < tracer id=2185 tags=download_handler.download_write args= 
768944 07:32:11.602794479 0 python (2185) < tracer id=2185 tags=download_handler args= 
784922 07:32:11.761646172 0 python (2194) > tracer id=2194 tags=empty_handler args= 
784924 07:32:11.761653837 0 python (2194) > tracer id=2194 tags=empty_handler.empty_headers args= 
785037 07:32:11.762354585 0 python (2194) < tracer id=2194 tags=empty_handler.empty_headers args= 
```

Attaching capture file.
[capture3.scap.zip](https://github.com/draios/sysdig/files/575821/capture3.scap.zip)

**Comment by ldegio** [comment]
First of all, support for this functionality was not available in sysdig. I just added it to the dev branch, so can you please try to build sysdig from that branch.

In addition, the correct syntax is:
```
$ sudo sysdig -r capture.scap -c fdbytes_by "evtin.span.tags"
```
because you want to use the events **inside** a span, not the ones identifying the span itself. Note that, if you want to aggregate at the script level, you will have to use _evtin.span.s.tags_ instead of evtin.span.tags. See https://github.com/draios/sysdig/wiki/Tracers#evtin-filter-fields for details.

Since the feature was not trivial to add, it would be great if you could let me know if this works as expected and, if it does, if you could update the tracers wiki page https://github.com/draios/sysdig/wiki/Tracers with some documentation.
