### ISSUE TITLE
Sysdig module in kernel upstream

### ISSUE THREAD

**Issue by jakubjedelsky** [draios/sysdig#81]
Is it possible to push sysdig kernel module to upstream tree? Some vendors uses secure boot so it isn't easy to load custom modules. Maybe I'm wrong but it should be much more easy if it will be loaded by distribution's kernel (eg. by Fedora).

**Comment by deathtrip** [comment]
any news on this?
It would be nice to get it upstream, and have sysdig work without needing to install extra modules.

**Comment by q2dg** [comment]
Same question three years later...
Thanks!!

**Comment by nathan-b** [comment]
If you are in an environment where custom kernel modules are difficult to load, you can try running with eBPF: https://github.com/draios/sysdig/wiki/eBPF

**Comment by q2dg** [comment]
NINE years later...without feedback

**Comment by nathan-b** [comment]
I don't think that's quite fair. Both Gianluca and I provided responses explaining the difficulty of the request and providing alternatives.

**Comment by deathtrip** [comment]
Is upstreaming even possible at this point?
As C++ code won't be accepted into the kernel. IIRC at the time of this issues creation sysdig was written in C.

**Comment by nathan-b** [comment]
The kernel module is still C code. Upstreaming is possible (though still difficult; last time we tried we didn't meet the criteria for inclusion in-tree). 

That said, with eBPF this concern is becoming less and less relevant, and eventually sysdig will be able to adopt the modern eBPF probe that Falco is currently finishing up (https://falco.org/blog/falco-modern-bpf/). This probe will utilize CO;RE / BTF technology along with libbpf in user space to be a true "run everywhere" probe which removes the need to either build your own kmod or pull one from the kernel. 

Rather than continuing to fight the fight for upstreaming the kernel module, we are hopeful that this solution will be a much more universal and effective solution for folks who are currently feeling the pain you are feeling :)

**Comment by therealbobo** [comment]
Actually we recently introduced the *experimental* modern bpf feature [#1963](https://github.com/draios/sysdig/pull/1963) ! :D 
Not all the syscalls are implemented yet but, in the near future, we hope the modern BPF probe will have the same capabilities of the kernel module :D
