### ISSUE TITLE
Multiple `connect` syscalls when only one is expected

### ISSUE THREAD

**Issue by arossert** [draios/sysdig#869]
I'm seeing something that I can't understand in sysdig output when looking at network syscalls.

This is the command that i'm using (added protocol to the output):

Command: `strace -o ipchicken curl www.ipchicken.com`

`sysdig -p "%evt.num %evt.outputtime %evt.cpu %proc.name (%threatid) %evt.dir %evt.type %evt.info %fd.l4proto" proc.name=curl and evt.category=net`

When I look at the output from sysdig I see multiple `connect` to the same destination (from different source ports) to port 80 using UDP (not making any sense).

When I compare this to strace output I see only one `connect` as expected.

Can you explain the multiple connects that sysdig reports but not shown in strace?
(I have attached the sysdig/strace output)

[curl_strace.txt](https://github.com/draios/sysdig/files/1086061/curl_strace.txt)
[curl_sysdig.txt](https://github.com/draios/sysdig/files/1086062/curl_sysdig.txt)

**Comment by gianlucaborello** [comment]
That should be because curl does the DNS/service name resolution in another thread, which is not caught with the normal invocation of strace, you should use `strace -f`. You will see a lot more connections and they should match the sysdig output, namely the one on port 53 for the DNS request, and another one on port 80 UDP which is the one that the libc uses internally during `getaddrinfo` to lookup the local address via `getsockname`, which is then used during the post-processing of the DNS results according to some RFC IIRC.

**Comment by arossert** [comment]
Thanks for the explanation

**Comment by arossert** [comment]
Sorry for reopening the issue, can you explain why I can't see this connection in `tcpdump`?
When using `tcpdump` I can't see any UDP connections on port 80

**Comment by gianlucaborello** [comment]
It's normal that you don't see any actual network activity. If you look at the stream of system calls on those sockets, you'll see that you have a `socket`, a `connect`, a `getsockname` and a `close`, no actual `send`/`receive`. None of those calls generate network packets when they operate on a UDP socket, curl is "connecting" the UDP socket just to make sure the kernel populates the socket structures needed by `getsockname`/`getpeername`, and then it closes it immediately.
