### ISSUE TITLE
evt.cpu=0 for evt.type=procinfo

### ISSUE THREAD

**Issue by osallou** [draios/sysdig#933]
Hi,
while filtering for procinfo evt types, I am surprised to always see evt.cpu=0.
for other events, I can see different cpus, but not for this time.
cpu.threads, container.name etc... are fine.

I wonder if this is a bug, a procinfo "feature", or something I do not understand in how sysdig manage events.

**Comment by osallou** [comment]
sysdig --version
sysdig version 0.16.0

**Comment by ldegio** [comment]
This is a "feature", or better a consequence of what procinfo is. Instead of being actual kernel events, like system calls or context switches, procinfo events are generated by scanning the process table, so they don't belong to a specific processor.

Even if we wanted to add cpu information to those events, it wouldn't be accurate because it's common for a thread to be on multiple CPUs during the procinfo observation inteval (typically 1 second).
